version: '3.9'

services:

  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      api:
        condition: service_completed_successfully
    restart: always

  api:
    build:
      context: ./
    env_file: .env
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/todolist/settings.py
    restart: always

  migrations:
    build:
      context: ./
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/migrations/__init__.py
    command: python manage.py migrate

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/docker-entrypoint-initdb.d